config/routes.rb
Rails.application.routes.draw do
  # get 'accounts/show'
  resources :accounts
  resources :transactions, only: [:new, :create, :index]
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users,  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:create]
  
  namespace :admin do
    resources :accounts
    resources :users
  end
  # get 'user/account', to: 'user_accounts#show', as: :user_account
  # get 'admin/account', to: 'admin_accounts#show', as: :admin_account
  # get 'superadmin/account', to: 'superadmin_accounts#show', as: :superadmin_account
  root 'pages#home' 
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, :all
      # Define other abilities for regular users
    end
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :transactions
  has_one_attached :image
  validates :phone, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :account
end

app/models/user.rb
class User < ApplicationRecord
  has_one :account
  has_many :transactions
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
  attribute :authenticated_from_google, :boolean, default: false

  before_create :set_default_role

  enum role: { user: "user", admin: "admin", superadmin: "superadmin" }
  
  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    unless user
        user = User.create(
           email: data['email'],
           password: Devise.friendly_token[0,20],
           authenticated_from_google: true
        )
    end
    user
  end
  
  
  private

  def set_default_role
    self.role ||= 'user'
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
    @account = current_user.account
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    @account.user = current_user

    if @account.save
      redirect_to root_path, notice: 'Account successfully created.'
    else
      render :new
    end
  end

  def update
    @account = Account.find(params[:id])
  
    if @account.update(account_params)
      redirect_to root_path, notice: 'Account details updated successfully.'
    else
      render :edit
    end
  end

  private

  def account_params
    params.require(:account).permit(:firstname, :lastname, :address, :dob, :phone, :gender, :balance, :image  )
  end
end

app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < ApplicationController
    before_action :authenticate_user!
  
    def index
      @users = User.all
      @accounts = Account.all
    end
  
    def show
      @account = Account.find(params[:id])
  
      
      @user = @account.user
      @accounts = Account.where(user_id: @user.id)
    end
    
  
    def edit
        @account = Account.find(params[:id])
        @user = @account.user
    end
  
    def update
      if @account.update(account_params)
        flash[:notice] = 'User account was successfully updated.'
        redirect_to admin_account_path(@account)
      else
        render :edit
      end
    end
  
    def destroy
        @account = Account.find(params[:id])
        @account.destroy
      flash[:notice] = 'User account was successfully deleted.'
      redirect_to admin_accounts_path
    end
  
    def new
      @account = Account.new
    end
  
    def create
      @account = Account.new(account_params)
      if @account.save
        flash[:notice] = 'User account was successfully created.'
        redirect_to admin_account_path(@account)
      else
        render :new
      end
    end
  
    private
  
    def account_params
      params.require(:account).permit(:firstname, :lastname, :address, :dob, :phone, :gender, :balance, :image)
    end
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session  
  before_action :configure_permitted_parameters, if: :devise_controller?
    def after_sign_in_path_for(resource)
      if resource.role == 'admin'
        admin_accounts_path
      else
        super
      end
    end
      helper_method :current_user
    
     
      
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password, :password_confirmation])
    end
  end
  

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    before_action :authenticate_user!
  
    def new
      @transaction = Transaction.new
    end
  
    def create  
      @transaction = current_user.transactions.build(transaction_params)
      @transaction.account = current_user.account
    
      if @transaction.save
        if @transaction.transaction_type == "Deposit"
          current_user.account.update(balance: current_user.account.balance + @transaction.amount)
        elsif @transaction.transaction_type == "Withdraw"
          current_balance = current_user.account.balance
          if current_balance >= @transaction.amount
            current_user.account.update(balance: current_balance - @transaction.amount)
          else
            flash[:alert] = "Insufficient balance."
            @transaction.destroy # Rollback the saved transaction
            render :new and return
          end
        end
        # Enqueue the email notification job
        TransactionMailer.transaction_notification(current_user, @transaction, current_user.account).deliver_now
        redirect_to transactions_path, notice: 'Transaction successfully processed.'
      else
        flash[:alert] = "Transaction couldn't be saved."
        render :new
      end
    end
    
    
    
  
    def index
      @transactions = current_user.transactions.order(created_at: :desc)
    end
  
    private
  
    def transaction_params
      params.require(:transaction).permit(:transaction_type, :amount)
    end
  end
  

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except('extra') 
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
end

app/controllers/users/users_controller.rb
class UsersController < ApplicationController
    def create
      @user = User.new(user_params)
      
      if @user.save
        redirect_to user_account_path
      else
        render :new
      end
    end
  
 
  
  end
  

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/_form.html.erb
<div class="container">
    <h1 class="well">Account Registration Form</h1>
	<div class="col-lg-12 well">
	<div class="row">
				 <%= form_with model: @account, url: accounts_path, method: :post, local: true, multipart: true do |f| %>
					<div class="col-sm-12">
						<div class="row">
							<div class="col-sm-6 form-group">
								<label>First Name</label>
								<%= f.text_field :firstname, class: "form-control" %>
							</div>
							<div class="col-sm-6 form-group">
								<label>Last Name</label>
								 <%= f.text_field :lastname, class: "form-control" %>
							</div>
						</div>					
						<div class="form-group">
							<label>Address</label>
							 <%= f.text_area :address, class: "form-control" %>
						</div>	
						<div class="row">
							<div class="col-sm-4 form-group">
								<label>DOB</label>
								 <%= f.date_field :dob, class: "form-control" %>
							</div>	
							<div class="col-sm-4 form-group">
                <label for="user_gender">Gender</label>
                 <%= f.select :gender, ['Male', 'Female', 'Other'], {}, class: "form-control" %>
                </div>

							<div class="col-sm-4 form-group">
                  <label for="user_image">Image</label>
                   <%= f.file_field :image, class: "form-control", id: "user_image" %>
                </div>
	
						</div>
						<div class="row">
							<div class="col-sm-6 form-group">
								<label>Balance</label>
								<%= f.number_field :balance, class: "form-control" %>
							</div>
              		
						<div class="col-sm-6 form-group">
						   <label>Phone Number</label>
					     <%= f.text_field :phone, class: "form-control" %> 
					  </div>		
					</div>						
				
					<div class="col-sm-4 form-group">
            <%= f.submit 'Create Account', class: "btn btn-lg btn-info" %>
            <%= link_to 'Back', root_path, class: "btn btn-lg btn-default" %>
          </div>
          </div>
				<%end%> 
				</div>
    	</div>
	</div>

app/views/accounts/destroy.html.erb
<h2>Confirm Account Deletion</h2>
<p>Are you sure you want to delete your account?</p>
<%= link_to 'Back', root_path %>
<%= button_to 'Delete', account_path(@account), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/accounts/edit.html.erb
<%= render 'form', account: @account %>

app/views/accounts/new.html.erb
<%= render 'form' %>

app/views/accounts/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <%= stylesheet_link_tag 'account.css'%>
    <title>Document</title>
  </head>
  <body>
    <div class="container bootstrap snippets bootdey">
      <div class="row">
        <div class="profile-nav col-md-3">
          <div class="panel">
            <div class="user-heading round">
              <a href="#">
                <% if @account.image.attached? %> <%= image_tag @account.image
                %> <% else %>
                <p>No image uploaded.</p>
                <% end %>
              </a>
              <h1><%= @account.firstname %></h1>
              <p><%= current_user.email %></p>
            </div>

            <ul class="nav nav-pills nav-stacked">
                <li class="active">
                    <%= link_to account_path(current_user.account) do %>
                    <i class="bi bi-person-circle"></i> Profile
                    <% end %>
                </li>
                <li>
                    <%= link_to root_path do %>
                    <i class="bi bi-house-door-fill"></i> Home Page
                    <% end %>
                </li>
                <li>
                    <%= link_to edit_account_path do %>
                    <i class="bi bi-pencil-square"></i> Edit profile
                    <% end %>
                </li>
                <li>
                    <%= link_to new_transaction_path do %>
                    <i class="bi bi-currency-dollar"></i> Make Transaction
                    <% end %>
                </li>
                <li>
                    <%= link_to transactions_path do %>
                    <i class="bi bi-clock-history"></i> History
                    <% end %>
                </li>
                <li>
                    <%= button_to destroy_user_session_path, method: :delete do %>
                    <i class="bi bi-box-arrow-left"></i> Logout
                    <% end %>
                </li>
            </ul>
          </div>
        </div>

        <div class="panel">
          <div class="bio-graph-heading">
            Welcome to EasyCash, where your financial security is our top
            priority. Experience seamless banking with innovative features and
            robust security measures
          </div>
          <div class="panel-body bio-graph-info">
            <h1>Your Account Details</h1>
            <div class="row">
              <div class="bio-row">
                <p><span>First Name </span>: <%= @account.firstname %></p>
              </div>
              <div class="bio-row">
                <p><span>Last Name </span>: <%= @account.lastname %></p>
              </div>
              <div class="bio-row">
                <p><span>Address </span>: <%= @account.address %></p>
              </div>
              <div class="bio-row">
                <p><span>Birthday</span>: <%= @account.dob %></p>
              </div>
              <div class="bio-row">
                <p><span>Gender </span>: <%= @account.gender %></p>
              </div>
              <div class="bio-row">
                <p><span>Mobile </span>: <%= @account.phone %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/admin/accounts/_form.html.erb
<div class="container">
    <h1 class="well">Account Registration Form</h1>
	<div class="col-lg-12 well">
	<div class="row">
          <%= form_with(model: admin_account, local: true) do |f| %>
					<div class="col-sm-12">
						<div class="row">
							<div class="col-sm-6 form-group">
								<label>First Name</label>
								<%= f.text_field :firstname, class: "form-control" %>
							</div>
							<div class="col-sm-6 form-group">
								<label>Last Name</label>
								 <%= f.text_field :lastname, class: "form-control" %>
							</div>
						</div>					
						<div class="form-group">
							<label>Address</label>
							 <%= f.text_area :address, class: "form-control" %>
						</div>	
						<div class="row">
							<div class="col-sm-4 form-group">
								<label>DOB</label>
								 <%= f.date_field :dob, class: "form-control" %>
							</div>	
							<div class="col-sm-4 form-group">
                <label for="user_gender">Gender</label>
                 <%= f.select :gender, ['Male', 'Female', 'Other'], {}, class: "form-control" %>
                </div>

							<div class="col-sm-4 form-group">
                  <label for="user_image">Image</label>
                   <%= f.file_field :image, class: "form-control", id: "user_image" %>
                </div>
	
						</div>
						<div class="row">
							<div class="col-sm-6 form-group">
								<label>Balance</label>
								<%= f.number_field :balance, class: "form-control" %>
							</div>
              		
						<div class="col-sm-6 form-group">
						   <label>Phone Number</label>
					     <%= f.text_field :phone, class: "form-control" %> 
					  </div>		
					</div>						
				
					<div class="col-sm-4 form-group">
            <%= f.submit 'Create Account', class: "btn btn-lg btn-info" %>
            <%= link_to 'Back', root_path, class: "btn btn-lg btn-default" %>
          </div>
          </div>
				<%end%> 
				</div>
    	</div>
	</div>

app/views/admin/accounts/delete.html.erb
<h1>Delete Account - <%= @user.email %></h1>

<p>Are you sure you want to delete this user's account?</p>

<%= link_to 'Cancel', admin_account_path(@user.account) %>
<%= link_to 'Delete', admin_account_path(@user.account), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/admin/accounts/edit.html.erb
<h2>Edit User Account</h2>

<%= render 'form', admin_account: @account %>

<%= link_to 'Back', admin_accounts_path %>

app/views/admin/accounts/index.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Admin Dashboard - User Accounts</h1>
  <table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td>
            <div class="btn-group" role="group">
              <%= link_to 'View Account', admin_account_path(user.account), class: 'btn btn-primary btn-sm mr-1' %>
              <%= link_to 'Edit Account', edit_admin_account_path(user.account), class: 'btn btn-warning btn-sm mr-1' %>
              <%# <%= link_to 'Delete Account', destroy_account_path(user.account), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/accounts/new.html.erb
<h2>Create User Account</h2>

<%= render 'form', admin_account: @account %>

<%= link_to 'Back', admin_accounts_path %>

app/views/admin/accounts/show.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Account Details - <%= @user.email %></h1>
  <h2 class="mb-3">Transaction History</h2>

  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th>Type</th>
        <th>Amount</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
      <% @user.transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.transaction_type %></td>
          <td><%= transaction.amount %></td>
          <td><%= transaction.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="bubble-chart mt-5">
    <% @accounts.each do |account| %>
      <div id="bubble-chart-<%= account.user.id %>" class="bubble-chart-container"></div>
    <% end %>
  </div>
</div>

<script>
document.addEventListener("DOMContentLoaded", function() {
  <% @accounts.each do |account| %> 
    var data<%= account.user.id %> = [
      <% account.transactions.each do |transaction| %>
        { amount: <%= transaction.amount %>, type: '<%= transaction.transaction_type %>', time: '<%= transaction.created_at %>' },
      <% end %>
    ];

    var margin = { top: 20, right: 20, bottom: 70, left: 40 };
    var width = 800 - margin.left - margin.right;
    var height = 400 - margin.top - margin.bottom;

    var xScale<%= account.user.id %> = d3.scaleBand()
      .domain(data<%= account.user.id %>.map(function(d) { return d.type; }))
      .range([0, width]);

    var yScale<%= account.user.id %> = d3.scaleLinear()
      .domain([0, d3.max(data<%= account.user.id %>, function(d) { return d.amount; })])
      .range([height, 0]);

    var rScale<%= account.user.id %> = d3.scaleLinear()
      .domain([0, d3.max(data<%= account.user.id %>, function(d) { return d.amount; })])
      .range([5, 20]);

    var svg<%= account.user.id %> = d3.select("#bubble-chart-<%= account.user.id %>")
      .append("svg")
      .attr("width", "100%")
      .attr("height", "100%")
      .attr("viewBox", "0 0 " + (width + margin.left + margin.right) + " " + (height + margin.top + margin.bottom))
      .attr("preserveAspectRatio", "xMidYMid meet")
      .append("g")
      .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

    // Create x-axis
    svg<%= account.user.id %>.append("g")
      .attr("transform", "translate(0," + height + ")")
      .call(d3.axisBottom(xScale<%= account.user.id %>))
      .selectAll("text")
      .style("text-anchor", "end")
      .attr("dx", "-.8em")
      .attr("dy", ".15em")
      .attr("transform", "rotate(-45)");

    // Create y-axis
    svg<%= account.user.id %>.append("g")
      .call(d3.axisLeft(yScale<%= account.user.id %>));

    svg<%= account.user.id %>.selectAll("circle")
      .data(data<%= account.user.id %>)
      .enter()
      .append("circle")
      .attr("cx", function(d) { return xScale<%= account.user.id %>(d.type); })
      .attr("cy", function(d) { return yScale<%= account.user.id %>(d.amount); })
      .attr("r", function(d) { return rScale<%= account.user.id %>(d.amount); })
      .style("fill", function(d) { return d.type === 'Deposit' ? 'blue' : 'red'; });
  <% end %>
});
</script>

<%= link_to 'All Users', admin_accounts_path, class: 'btn btn-primary mt-4' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BankApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> 
<link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"
    />    
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

      <script src="https://d3js.org/d3.v7.min.js"></script>
    <%= javascript_include_tag 'bubble_chart' %>
    <%= csp_meta_tag %> 
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
    <%= javascript_importmap_tags%>
     <%= stylesheet_link_tag 'devise_messages.css'%>
  </head>

  <body>
    <div class="fixed-top">
      <% flash.each do |key, value| %>
      <div class="alert <%= key == 'notice' ? 'alert-success' : 'alert-danger' %> alert-dismissible fade show" role="alert">
        <%= value %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/transactions/_transaction_form.html.erb
  <div class="container mt-5">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@transaction, url: transactions_path) do |f| %>
          <%= f.hidden_field :transaction_type, value: action_name.capitalize %>
          
          <div class="mb-3">
            <h3 class="mb-4">Transaction Form</h3>
            <p><strong>Current Balance:</strong> $<%= current_user.account.balance %></p>
          </div>
          
          <div class="form-group">
            <%= f.label :amount %>
            <%= f.text_field :amount, class: "form-control" %>
          </div>
          
          <div class="form-group">
            <%= f.label :transaction_type %>
            <%= f.select :transaction_type, ['Deposit', 'Withdraw'], { prompt: 'Select transaction type' }, class: "form-control" %>
          </div>
          
          <div class="mb-3 text-center">
            <%= f.submit 'Submit', class: "btn btn-primary" %>
          </div>
        <% end %>
        <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>">
            <%= value %>
            </div>
        <% end %>

      </div>
    </div>
  </div>

app/views/transactions/index.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Transaction History</h1>
  
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Type</th>
        <th>Amount</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
      <% @transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.transaction_type %></td>
          <td><%= transaction.amount %></td>
          <td><%= transaction.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/transactions/new.html.erb
<h1>Create Transaction</h1>

<%= render 'transaction_form' %>